v1:
  token:
    "auth/%s/create":
      post:
        id: false
        params:
          - name: "id"
            type: "string"
            required: false
          - name: "policies"
            type: "list"
            required: false
          - name: "meta"
            type: "object"
            required: false
          - name: "no_parent"
            type: "bool"
            required: false
          - name: "ttl"
            type: "duration"
            required: false
          - name: "display_name"
            type: "string"
            required: false
          - name: "num_uses"
            type: "number"
            required: false
    "auth/%s/lookup-self":
      get:
        id: false
        params: []
    "auth/%s/lookup/:id":
      get:
        id: true
        params: []
    "auth/%s/revoke/:id":
      post:
        id: true
        params: []
    "auth/%s/revoke-self":
      post:
        id: false
        params: []
    "auth/%s/revoke-orphan/:id":
      post:
        id: true
        params: []
    "auth/%s/revoke-prefix/:id":
      post:
        id: true
        params: []
    "auth/%s/renew/:id":
      post:
        id: true
        params:
          - name: "increment"
            type: "number"
            required: false
    "auth/%s/renew-self":
      post:
        id: false
        params:
          - name: "increment"
            type: "number"
            required: false
  app-id:
    "auth/%s/map/app-id/:id":
      post:
        id: true
        params:
          - name: "value"
            type: "string"
            required: true
          - name: "display_name"
            type: "string"
            required: true
      get:
        id: true
        params: []
      delete:
        id: true
        params: []
    "auth/%s/map/user-id/:id":
      post:
        id: true
        params:
          - name: "value"
            type: "string"
            required: true
          - name: "cidr_block"
            type: "string"
            required: false
      get:
        id: true
        params: []
      delete:
        id: true
        params: []
    "auth/%s/login":
      post:
        id: false
        params:
          - name: "app_id"
            type: "string"
            required: true
          - name: "user_id"
            type: "string"
            required: true
  secret:
    "%s/:id":
      get:
        id: true
        params: []
      put:
        id: true
        params: []
      delete:
        id: true
        params: []
  consul:
    "%s/config/access":
      post:
        id: false
        params:
          - name: "address"
            type: "string"
            required: true
          - name: "scheme"
            type: "string"
            required: false
          - name: "token"
            type: "string"
            required: true
    "%s/roles/:id":
      post:
        id: true
        params:
          - name: "policy"
            type: "string"
            required: true
          - name: "token_type"
            type: "string"
            required: false
          - name: "lease"
            type: "duration"
            required: false
      get:
        id: true
        params: []
      delete:
        id: true
        params: []
    "%s/creds/:id":
      get:
        id: true
        params: []
  pki:
    "%s/ca":
      get:
        id: false
        params: []
    "%s/ca/pem":
      get:
        id: false
        params: []
    "%s/cert/ca":
      get:
        id: false
        params: []
    "%s/cert/crl":
      get:
        id: false
        params: []
    "%s/cert/:id":
      get:
        id: true
        params: []
    "%s/config/ca":
      post:
        id: false
        params:
          - name: "pem_bundle"
            type: "string"
            required: true
    "%s/config/crl":
      get:
        id: false
        params: []
      post:
        id: false
        params:
          - name: "expiry"
            type: "duration"
            required: true
    "%s/config/urls":
      get:
        id: false
        params: []
      post:
        id: false
        params:
          - name: "issuing_certificates"
            type: "string"
            required: false
          - name: "crl_distribution_points"
            type: "string"
            required: false
          - name: "ocsp_servers"
            type: "string"
            required: false
    "%s/crl":
      get:
        id: false
        params: []
    "%s/crl/pem":
      get:
        id: false
        params: []
    "%s/crl/rotate":
      get:
        id: false
        params: []
    "%s/intermediate/generate/exported":
      post:
        id: false
        params:
          - name: "common_name"
            type: "string"
            required: true
          - name: "alt_names"
            type: "string"
            required: false
          - name: "ip_sans"
            type: "string"
            required: false
          - name: "format"
            type: "string"
            required: false
          - name: "key_type"
            type: "string"
            required: false
          - name: "key_bits"
            type: "string"
            required: false
    "%s/intermediate/generate/internal":
      post:
        id: false
        params:
          - name: "common_name"
            type: "string"
            required: true
          - name: "alt_names"
            type: "string"
            required: false
          - name: "ip_sans"
            type: "string"
            required: false
          - name: "format"
            type: "string"
            required: false
          - name: "key_type"
            type: "string"
            required: false
          - name: "key_bits"
            type: "string"
            required: false
    "%s/intermediate/set-signed":
      post:
        id: false
        params:
          - name: "certificate"
            type: "string"
            required: true
    "%s/issue/:id":
      post:
        id: true
        params:
          - name: "common_name"
            type: "string"
            required: true
          - name: "alt_names"
            type: "string"
            required: false
          - name: "ip_sans"
            type: "string"
            required: false
          - name: "ttl"
            type: "duration"
            required: false
          - name: "format"
            type: "string"
            required: false
    "%s/revoke":
      post:
        id: false
        params:
          - name: "serial_number"
            type: "string"
            required: true
    "%s/roles/:id":
      post:
        id: true
        params:
          - name: "ttl"
            type: "duration"
            required: false
          - name: "max_ttl"
            type: "duration"
            required: false
          - name: "allow_localhost"
            type: "bool"
            required: false
          - name: "allowed_domains"
            type: "string"
            required: false
          - name: "allow_bare_domains"
            type: "bool"
            required: false
          - name: "allow_subdomains"
            type: "bool"
            required: false
          - name: "allow_any_name"
            type: "bool"
            required: false
          - name: "enforce_hostnames"
            type: "bool"
            required: false
          - name: "allow_ip_sans"
            type: "bool"
            required: false
          - name: "server_flag"
            type: "bool"
            required: false
          - name: "client_flag"
            type: "bool"
            required: false
          - name: "code_signing_flag"
            type: "bool"
            required: false
          - name: "email_protection_flag"
            type: "bool"
            required: false
          - name: "key_type"
            type: "string"
            required: false
          - name: "key_bits"
            type: "string"
            required: false
          - name: "use_csr_common_name"
            type: "bool"
            required: false
      get:
        id: true
        params: []
      delete:
        id: true
        params: []
    "%s/root/generate/exported":
      post:
        id: false
        params:
          - name: "common_name"
            type: "string"
            required: true
          - name: "alt_names"
            type: "string"
            required: false
          - name: "ip_sans"
            type: "string"
            required: false
          - name: "ttl"
            type: "duration"
            required: false
          - name: "format"
            type: "string"
            required: false
          - name: "key_type"
            type: "string"
            required: false
          - name: "key_bits"
            type: "string"
            required: false
          - name: "max_path_length"
            type: "number"
            required: false
    "%s/root/generate/internal":
      post:
        id: false
        params:
          - name: "common_name"
            type: "string"
            required: true
          - name: "alt_names"
            type: "string"
            required: false
          - name: "ip_sans"
            type: "string"
            required: false
          - name: "ttl"
            type: "duration"
            required: false
          - name: "format"
            type: "string"
            required: false
          - name: "key_type"
            type: "string"
            required: false
          - name: "key_bits"
            type: "string"
            required: false
          - name: "max_path_length"
            type: "number"
            required: false
    "%s/root/sign-intermediate":
      post:
        id: false
        params:
          - name: "csr"
            type: "string"
            required: true
          - name: "common_name"
            type: "string"
            required: true
          - name: "alt_names"
            type: "string"
            required: false
          - name: "ip_sans"
            type: "string"
            required: false
          - name: "ttl"
            type: "duration"
            required: false
          - name: "format"
            type: "string"
            required: false
          - name: "max_path_length"
            type: "number"
            required: false
          - name: "use_csr_values"
            type: "bool"
            required: false
    "%s/sign/:id":
      post:
        id: true
        params:
          - name: "csr"
            type: "string"
            required: true
          - name: "common_name"
            type: "string"
            required: true
          - name: "alt_names"
            type: "string"
            required: false
          - name: "ip_sans"
            type: "string"
            required: false
          - name: "ttl"
            type: "duration"
            required: false
          - name: "format"
            type: "string"
            required: false
    "%s/sign-verbatim":
      post:
        id: false
        params:
          - name: "csr"
            type: "string"
            required: true
          - name: "ttl"
            type: "duration"
            required: false
          - name: "format"
            type: "string"
            required: false
  transit:
      "%s/keys/:id":
        get:
          id: true
          params: []
        post:
          id: true
          params:
            - name: "derived"
              type: "bool"
              required: false
            - name: "convergent_encryption"
              type: "bool"
              required: false
        delete:
          id: true
          params: []
      "%s/keys/:id/config":
        post:
          id: true
          params:
            - name: "min_decryption_version"
              type: "number"
              required: false
            - name: "deletion_allowed"
              type: "bool"
              required: false
      "%s/keys/:id/rotate":
        post:
          id: true
          params: []
      "%s/encrypt/:id":
        post:
          id: true
          params:
            - name: "plaintext"
              type: "string"
              required: true
            - name: "context"
              type: "string"
              required: false
            - name: "nonce"
              type: "string"
              required: false
      "%s/decrypt/:id":
        post:
          id: true
          params:
            - name: "ciphertext"
              type: "string"
              required: true
            - name: "context"
              type: "string"
              required: false
            - name: "nonce"
              type: "string"
              required: false
      "%s/rewrap/:id":
        post:
          id: true
          params:
            - name: "ciphertext"
              type: "string"
              required: true
            - name: "context"
              type: "string"
              required: false
            - name: "nonce"
              type: "string"
              required: false
      "%s/datakey/plaintext/:id":
        post:
          id: true
          params:
            - name: "context"
              type: "string"
              required: false
            - name: "nonce"
              type: "string"
              required: false
            - name: "bits"
              type: "number"
              required: false
      "%s/datakey/wrapped/:id":
        post:
          id: true
          params:
            - name: "context"
              type: "string"
              required: false
            - name: "nonce"
              type: "string"
              required: false
            - name: "bits"
              type: "number"
              required: false
